twig:
    default_path: '%kernel.project_dir%/templates'
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'

    form_themes: ['bootstrap_4_layout.html.twig']
    date:
        format: d/m/Y
        interval_format: '%%d días'
        timezone: America/Managua
    number_format:
        decimals: 2
        decimal_point: '.'
        thousands_separator: ','